import random

# 模拟多版本的成功率数据
version_list = ["v1", "v2", "v3"]
# 多版本成功率数据
multi_version_success_rate_data = [
    {
        "grip_pose": "单手握持-左手",
        "hit_position": "敲击靠上区域",
        "id": 1,
        "motion_scene": "静止",
        "name": "AP1",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),

    },
    {
        "grip_pose": "单手握持-左手",
        "hit_position": "敲击靠中区域",
        "id": 1,
        "motion_scene": "静止",
        "name": "AP2",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "单手握持-右手",
        "hit_position": "敲击靠上区域",
        "id": 2,
        "motion_scene": "静止",
        "name": "AP3",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "单手握持-右手",
        "hit_position": "敲击靠中区域",
        "id": 2,
        "motion_scene": "静止",
        "name": "AP4",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "左手握持-右手敲",
        "hit_position": "敲击靠上区域",
        "id": 3,
        "motion_scene": "静止",
        "name": "AP5",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "左手握持-右手敲",
        "hit_position": "敲击靠中区域",
        "id": 3,
        "motion_scene": "静止",
        "name": "AP6",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "右手握持-左手敲",
        "hit_position": "敲击靠上区域",
        "id": 4,
        "motion_scene": "静止",
        "name": "AP7",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "右手握持-左手敲",
        "hit_position": "敲击靠中区域",
        "id": 4,
        "motion_scene": "静止",
        "name": "AP8",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "头朝左-双手握持-左手敲",
        "hit_position": "任意位置",
        "id": 5,
        "motion_scene": "静止",
        "name": "AP9",
        "orientation": "横屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "头朝左-双手握持-右手敲",
        "hit_position": "任意位置",
        "id": 6,
        "motion_scene": "静止",
        "name": "AP10",
        "orientation": "横屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "头朝右-双手握持-左手敲",
        "hit_position": "任意位置",
        "id": 7,
        "motion_scene": "静止",
        "name": "AP11",
        "orientation": "横屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "头朝右-双手握持-右手敲",
        "hit_position": "任意位置",
        "id": 8,
        "motion_scene": "静止",
        "name": "AP12",
        "orientation": "横屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "单手握持-左手",
        "hit_position": "敲击靠上区域",
        "id": 9,
        "motion_scene": "走路",
        "name": "AP13",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "单手握持-左手",
        "hit_position": "敲击靠中区域",
        "id": 9,
        "motion_scene": "走路",
        "name": "AP14",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "单手握持-右手",
        "hit_position": "敲击靠上区域",
        "id": 10,
        "motion_scene": "走路",
        "name": "AP15",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "单手握持-右手",
        "hit_position": "敲击靠中区域",
        "id": 10,
        "motion_scene": "走路",
        "name": "AP16",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "左手握持-右手敲",
        "hit_position": "敲击靠上区域",
        "id": 11,
        "motion_scene": "走路",
        "name": "AP17",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "左手握持-右手敲",
        "hit_position": "敲击靠中区域",
        "id": 11,
        "motion_scene": "走路",
        "name": "AP18",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "右手握持-左手敲",
        "hit_position": "敲击靠上区域",
        "id": 12,
        "motion_scene": "走路",
        "name": "AP19",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "右手握持-左手敲",
        "hit_position": "敲击靠中区域",
        "id": 12,
        "motion_scene": "走路",
        "name": "AP20",
        "orientation": "竖屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "头朝左-双手握持-左手敲",
        "hit_position": "任意位置",
        "id": 13,
        "motion_scene": "走路",
        "name": "AP21",
        "orientation": "横屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "头朝左-双手握持-右手敲",
        "hit_position": "任意位置",
        "id": 14,
        "motion_scene": "走路",
        "name": "AP22",
        "orientation": "横屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "头朝右-双手握持-左手敲",
        "hit_position": "任意位置",
        "id": 15,
        "motion_scene": "走路",
        "name": "AP23",
        "orientation": "横屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    },
    {
        "grip_pose": "头朝右-双手握持-右手敲",
        "hit_position": "任意位置",
        "id": 16,
        "motion_scene": "走路",
        "name": "AP24",
        "orientation": "横屏",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),

    },
    {
        "name": "all",
        "v1-successCount": random.randint(0, 100),
        "v1-totalCount": random.randint(0, 100),
        "v1-successRate": random.uniform(0, 1),
        "v2-successCount": random.randint(0, 100),
        "v2-totalCount": random.randint(0, 100),
        "v2-successRate": random.uniform(0, 1),
        "v3-successCount": random.randint(0, 100),
        "v3-totalCount": random.randint(0, 100),
        "v3-successRate": random.uniform(0, 1),
    }
]
# 多版本误触数据
multi_version_fail_data = [
    {
        "id": 1,
        "motion_scene": "拿放手机亮屏解锁状态下，将手机放至桌面上，再拿起手机",
        "name": "AN1",
        "v1-error_count": random.randint(0, 100),
        "v2-error_count": random.randint(0, 100),
        "v3-error_count": random.randint(0, 100),

    },

    {
        "id": 2,
        "motion_scene": "换手握持静止状态，坐姿亮屏解锁状态下换手握持手机",
        "name": "AN2",
        "v1-error_count": random.randint(0, 100),
        "v2-error_count": random.randint(0, 100),
        "v3-error_count": random.randint(0, 100),
    },

    {
        "id": 3,
        "motion_scene": "换手握尺走路场景亮屏，解锁状态下浏览手机后换手握智手机。",
        "name": "AN3",
        "v1-error_count": random.randint(0, 100),
        "v2-error_count": random.randint(0, 100),
        "v3-error_count": random.randint(0, 100),
    },

    {
        "id": 4,
        "motion_scene": "握姿调整亮屏解锁状态下，浏览手机后按个人习惯调整握姿。",
        "name": "AN4",
        "v1-error_count": random.randint(0, 100),
        "v2-error_count": random.randint(0, 100),
        "v3-error_count": random.randint(0, 100),
    },

    {
        "id": 5,
        "motion_scene": "手机主动敲击亮屏解锁状态下，用手机背部中心四脚敲击两下桌面。",
        "name": "AN5",
        "v1-error_count": random.randint(0, 100),
        "v2-error_count": random.randint(0, 100),
        "v3-error_count": random.randint(0, 100),
    },

    {
        "id": 6,
        "motion_scene": "手机主动敲击亮屏解锁状态下，用手机背部中心四脚敲击两下手指或手心。",
        "name": "AN6",
        "v1-error_count": random.randint(0, 100),
        "v2-error_count": random.randint(0, 100),
        "v3-error_count": random.randint(0, 100),
    },

    {
        "id": 7,
        "motion_scene": "按键亮屏解锁状态下模拟快速调节音量时连续按音量键。",
        "name": "AN7",
        "v1-error_count": random.randint(0, 100),
        "v2-error_count": random.randint(0, 100),
        "v3-error_count": random.randint(0, 100),
    },

    {
        "id": 8,
        "motion_scene": "开合手机亮屏解锁状态下反复开合手机。",
        "name": "AN8",
        "v1-error_count": random.randint(0, 100),
        "v2-error_count": random.randint(0, 100),
        "v3-error_count": random.randint(0, 100),
    },

    {
        "id": 9,
        "motion_scene": "正面敲击亮屏，解锁状态下敲击屏幕。",
        "name": "AN9",
        "v1-error_count": random.randint(0, 100),
        "v2-error_count": random.randint(0, 100),
        "v3-error_count": random.randint(0, 100),
    },

    {
        "id": 10,
        "motion_scene": "侧边敲击亮屏解锁状态下敲击手机侧边框。",
        "name": "AN10",
        "v1-error_count": random.randint(0, 100),
        "v2-error_count": random.randint(0, 100),
        "v3-error_count": random.randint(0, 100),
    },

    {
        "name": "all",
        "v1-error_count": random.randint(0, 100),
        "v2-error_count": random.randint(0, 100),
        "v3-error_count": random.randint(0, 100),
    }
]

# 单版本成功率数据
single_version_success_rate_data = [
    {
        "grip_pose": "单手握持-左手",
        "hit_position": "敲击靠上区域",
        "id": 1,
        "motion_scene": "静止",
        "name": "AP1",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "单手握持-左手",
        "hit_position": "敲击靠中区域",
        "id": 1,
        "motion_scene": "静止",
        "name": "AP2",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "单手握持-右手",
        "hit_position": "敲击靠上区域",
        "id": 2,
        "motion_scene": "静止",
        "name": "AP3",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "单手握持-右手",
        "hit_position": "敲击靠中区域",
        "id": 2,
        "motion_scene": "静止",
        "name": "AP4",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "左手握持-右手敲",
        "hit_position": "敲击靠上区域",
        "id": 3,
        "motion_scene": "静止",
        "name": "AP5",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "左手握持-右手敲",
        "hit_position": "敲击靠中区域",
        "id": 3,
        "motion_scene": "静止",
        "name": "AP6",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "右手握持-左手敲",
        "hit_position": "敲击靠上区域",
        "id": 4,
        "motion_scene": "静止",
        "name": "AP7",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "右手握持-左手敲",
        "hit_position": "敲击靠中区域",
        "id": 4,
        "motion_scene": "静止",
        "name": "AP8",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "头朝左-双手握持-左手敲",
        "hit_position": "任意位置",
        "id": 5,
        "motion_scene": "静止",
        "name": "AP9",
        "orientation": "横屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "头朝左-双手握持-右手敲",
        "hit_position": "任意位置",
        "id": 6,
        "motion_scene": "静止",
        "name": "AP10",
        "orientation": "横屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "头朝右-双手握持-左手敲",
        "hit_position": "任意位置",
        "id": 7,
        "motion_scene": "静止",
        "name": "AP11",
        "orientation": "横屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "头朝右-双手握持-右手敲",
        "hit_position": "任意位置",
        "id": 8,
        "motion_scene": "静止",
        "name": "AP12",
        "orientation": "横屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "单手握持-左手",
        "hit_position": "敲击靠上区域",
        "id": 9,
        "motion_scene": "走路",
        "name": "AP13",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "单手握持-左手",
        "hit_position": "敲击靠中区域",
        "id": 9,
        "motion_scene": "走路",
        "name": "AP14",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "单手握持-右手",
        "hit_position": "敲击靠上区域",
        "id": 10,
        "motion_scene": "走路",
        "name": "AP15",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "单手握持-右手",
        "hit_position": "敲击靠中区域",
        "id": 10,
        "motion_scene": "走路",
        "name": "AP16",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "左手握持-右手敲",
        "hit_position": "敲击靠上区域",
        "id": 11,
        "motion_scene": "走路",
        "name": "AP17",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "左手握持-右手敲",
        "hit_position": "敲击靠中区域",
        "id": 11,
        "motion_scene": "走路",
        "name": "AP18",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "右手握持-左手敲",
        "hit_position": "敲击靠上区域",
        "id": 12,
        "motion_scene": "走路",
        "name": "AP19",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "右手握持-左手敲",
        "hit_position": "敲击靠中区域",
        "id": 12,
        "motion_scene": "走路",
        "name": "AP20",
        "orientation": "竖屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "头朝左-双手握持-左手敲",
        "hit_position": "任意位置",
        "id": 13,
        "motion_scene": "走路",
        "name": "AP21",
        "orientation": "横屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "头朝左-双手握持-右手敲",
        "hit_position": "任意位置",
        "id": 14,
        "motion_scene": "走路",
        "name": "AP22",
        "orientation": "横屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "头朝右-双手握持-左手敲",
        "hit_position": "任意位置",
        "id": 15,
        "motion_scene": "走路",
        "name": "AP23",
        "orientation": "横屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "grip_pose": "头朝右-双手握持-右手敲",
        "hit_position": "任意位置",
        "id": 16,
        "motion_scene": "走路",
        "name": "AP24",
        "orientation": "横屏",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    },
    {
        "name": "all",
        "successCount": random.randint(0, 100),
        "totalCount": random.randint(0, 100),
        "successRate": random.uniform(0, 1)
    }
]

# 单版本错误数据
single_version_fail_data = [
    {
        "id": 1,
        "motion_scene": "拿放手机亮屏解锁状态下，将手机放至桌面上，再拿起手机",
        "name": "AN1",
        "error_count": random.randint(0, 100)
    },

    {
        "id": 2,
        "motion_scene": "换手握持静止状态，坐姿亮屏解锁状态下换手握持手机",
        "name": "AN2",
        "error_count": random.randint(0, 100)
    },

    {
        "id": 3,
        "motion_scene": "换手握尺走路场景亮屏，解锁状态下浏览手机后换手握智手机。",
        "name": "AN3",
        "error_count": random.randint(0, 100)
    },

    {
        "id": 4,
        "motion_scene": "握姿调整亮屏解锁状态下，浏览手机后按个人习惯调整握姿。",
        "name": "AN4",
        "error_count": random.randint(0, 100)
    },

    {
        "id": 5,
        "motion_scene": "手机主动敲击亮屏解锁状态下，用手机背部中心四脚敲击两下桌面。",
        "name": "AN5",
        "error_count": random.randint(0, 100)
    },

    {
        "id": 6,
        "motion_scene": "手机主动敲击亮屏解锁状态下，用手机背部中心四脚敲击两下手指或手心。",
        "name": "AN6",
        "error_count": random.randint(0, 100)
    },

    {
        "id": 7,
        "motion_scene": "按键亮屏解锁状态下模拟快速调节音量时连续按音量键。",
        "name": "AN7",
        "error_count": random.randint(0, 100)
    },

    {
        "id": 8,
        "motion_scene": "开合手机亮屏解锁状态下反复开合手机。",
        "name": "AN8",
        "error_count": random.randint(0, 100)
    },

    {
        "id": 9,
        "motion_scene": "正面敲击亮屏，解锁状态下敲击屏幕。",
        "name": "AN9",
        "error_count": random.randint(0, 100)
    },

    {
        "id": 10,
        "motion_scene": "侧边敲击亮屏解锁状态下敲击手机侧边框。",
        "name": "AN10",
        "error_count": random.randint(0, 100)
    },

    {
        "name": "all",
        "error_count": random.randint(0, 100)
    }
]
